CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --do_train True \
    --model_name_or_path Qwen1.5-0.5B-Chat \
    --finetuning_type full \
    --template qwen \
    --dataset_dir data \
    --dataset oaast_sft_zh \
    --cutoff_len 1024 \
    --learning_rate 5e-05 \
    --num_train_epochs 1.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 10 \
    --save_steps 500 \
    --warmup_steps 0 \
    --output_dir saves/Qwen1.5-0.5B-Chat/full/train_2024-03-02-19-34-18 \
    --plot_loss True 
